CREATE TABLE IF NOT EXISTS `ArrestsCacheTable2` (
  `arrest_stats_id` int(11) NOT NULL DEFAULT '0',
  `Date` date DEFAULT NULL,
  `Team` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Team_name` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `Team_preffered_name` varchar(55) COLLATE utf8_unicode_ci NOT NULL,
  `Team_city` varchar(35) COLLATE utf8_unicode_ci NOT NULL,
  `Team_logo_id` int(11) NOT NULL,
  `Team_Conference` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Team_Division` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Team_Conference_Division` varchar(9) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Team_hex_color` varchar(6) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT 'The hex value that represents the team main color, without the preceding # hash symbol',
  `Team_hex_alt_color` varchar(6) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT 'The hex value that represents the team second color, without the preceding # hash symbol',
  `reddit_group_id` int(11) NOT NULL COMMENT 'Reddit Group ID',
  `Name` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Position` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Position_name` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `Position_type` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'O = offense, D = Defense, S = special teams',
  `Encounter` varchar(12) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Category` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Crime_category` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `Crime_category_color` varchar(6) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `Description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Outcome` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Season` year(4) NOT NULL DEFAULT '0000',
  `ArrestSeasonState` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `general_category_id` int(11) NOT NULL,
  `legal_level_id` int(11) NOT NULL,
  `resolution_category_id` int(11) NOT NULL,
  `Year` int(4) DEFAULT NULL,
  `Month` int(2) DEFAULT NULL,
  `Day` int(2) DEFAULT NULL,
  `Day_of_Week` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Day_of_Week_int` int(1) DEFAULT NULL,
  `DaysSince` bigint(21) DEFAULT NULL,
  `DaysToLastArrest` bigint(21) DEFAULT NULL,
  `DaysToLastCrimeArrest` bigint(21) DEFAULT NULL,
  `DaysToLastTeamArrest` bigint(21) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;