INSERT INTO `teams` (`teams_id`, `teams_full_name`, `Team_preffered_name`, `team_code`, `city`, `state`, `division`, `bandwagon_code`, `Team_logo_id`, `reddit_group_id`) VALUES
(6, 'Bengals', 'Cincinnati Bengals', 'CIN', 'Cincinnati', 'Ohio', 'NFL', 1, 7, 2),
(5, 'Broncos', 'Denver Broncos', 'DEN', 'Denver', 'Colorado', 'NFL', 2, 10, 3),
(4, 'Vikings', 'Minnesota Vikings', 'MIN', 'Minneapolis', 'Minnesota', 'NFL', 31, 18, 4),
(7, 'Buccaneers', 'Tampa Bay Buccaneers', 'TB', 'Tampa Bay', 'Florida', 'NFL', 4, 30, 4),
(8, 'Titans', 'Tennessee Titans', 'TEN', 'Nashville', 'Tennessee', 'NFL', 30, 31, 4),
(9, 'Jaguars', 'Jacksonville Jaguars', 'JAC', 'Jacksonville', 'Florida', 'NFL', 15, 15, 2),
(10, 'Colts', 'Indianapolis Colts', 'IND', 'Indianapolis', 'Indiana', 'NFL', 9, 14, 3),
(11, 'Bears', 'Chicago Bears', 'CHI', 'Chicago', 'Illinois', 'NFL', 0, 6, 5),
(12, 'Chiefs', 'Kansas City Chiefs', 'KC', 'Kansas City', 'Missouri', 'NFL', 8, 16, 6),
(13, 'Dolphins', 'Miami Dolphins', 'MIA', 'Miami', 'Florida', 'NFL', 11, 17, 3),
(14, 'Browns', 'Cleveland Browns', 'CLE', 'Cleveland', 'Ohio', 'NFL', 3, 8, 6),
(15, 'Chargers', 'Los Angeles Chargers', 'LAC', 'Los Angeles', 'California', 'NFL', 7, 26, 3),
(16, 'Ravens', 'Baltimore Ravens', 'BAL', 'Baltimore', 'Maryland', 'NFL', 24, 3, 1),
(17, 'Steelers', 'Pittsburgh Steelers', 'PIT', 'Pittsburgh', 'Pennsylvania', 'NFL', 28, 25, 5),
(18, 'Saints', 'New Orleans Saints', 'NO', 'New Orleans', 'Louisiana', 'NFL', 26, 20, 6),
(19, 'Seahawks', 'Seattle Seahawks', 'SEA', 'Seattle', 'Washington', 'NFL', 27, 28, 1),
(20, 'Packers', 'Green Bay Packers', 'GB', 'Green Bay', 'Wisconsin', 'NFL', 19, 12, 5),
(22, 'Raiders', 'Oakland Raiders', 'OAK', 'Oakland', 'California', 'NFL', 22, 23, 4),
(23, 'Redskins', 'Washington Redskins', 'WAS', 'Washington DC', 'USA', 'NFL', 25, 32, 4),
(24, 'Falcons', 'Atlanta Falcons', 'ATL', 'Atlanta', 'Georgia', 'NFL', 13, 2, 1),
(25, 'Cardinals', 'Arizona Cardinals', 'ARI', 'Phoenix', 'Arizona', 'NFL', 6, 1, 1),
(26, 'Panthers', 'Carolina Panthers', 'CAR', 'Charlotte', 'North Carolina', 'NFL', 20, 5, 2),
(27, 'Patriots', 'New England Patriots', 'NE', 'Boston', 'Massachusetts', 'NFL', 21, 19, 5),
(28, 'Buffalo Bills', 'Buffalo Bills', 'BUF', 'Buffalo', 'New York', 'NFL', 5, 4, 3),
(29, 'Lions', 'Detroit Lions', 'DET', 'Detroit', 'Michigan', 'NFL', 17, 11, 2),
(30, 'Cowboys', 'Dallas Cowboys', 'DAL', 'Dallas', 'Texas', 'NFL', 10, 9, 5),
(31, 'Jets', 'New York Jets', 'NYJ', 'New York', 'New York', 'NFL', 16, 22, 6),
(32, 'Eagles', 'Philadelphia Eagles', 'PHI', 'Philadelphia', 'Pennsylvania', 'NFL', 12, 24, 1),
(33, 'NY Giants', 'New York Giants', 'NYG', 'New York', 'New York', 'NFL', 18, 21, 0),
(34, 'Texans', 'Houston Texans', 'HOU', 'Houston', 'Texas', 'NFL', 29, 13, 3),
(35, 'Rams', 'Los Angeles Rams', 'LA', 'Los Angeles', 'California', 'NFL', 23, 29, 3),
(36, 'Free Agents', 'Free Agents', 'FREE', 'N/A', 'N/A', 'NFL', 99, 0, 0),
(37, '49ers', 'San Francisco 49ers', 'SF', 'San Francisco', 'California', 'NFL', 14, 27, 5);
